import {getCurrentUser, logout} from "./auth.js";
import {setProfileDisplay} from "./display-utils.js";

const api="https://ba2lg9ckm9.execute-api.ap-northeast-1.amazonaws.com/users/me";
const value=document.getElementById("display-name-value"),input=document.getElementById("display-name");
const actions=document.getElementById("profile-actions"),edit=document.getElementById("edit-button"),message=document.getElementById("status-message");
let user,original="",dirty=false,saving=false;
function editing(enabled){value.hidden=enabled;input.hidden=!enabled;actions.hidden=!enabled;edit.hidden=enabled;if(enabled)input.focus();}
function validate(name){const trimmed=name.trim();if(!trimmed)return "表示名を入力してください";if([...trimmed].length>50)return "表示名は50文字以内で入力してください";return "";}
async function init(){user=await getCurrentUser();if(!user||user.expired){location.href="index.html";return;}setProfileDisplay(document.getElementById("user-status"),user,"ログイン中：");try{const response=await fetch(api,{headers:{Authorization:`Bearer ${user.access_token}`}}),data=await response.json();if(!response.ok)throw new Error(data.message);const profile=data.user||{};original=profile.display_name||"";value.textContent=original||"未設定";input.value=original;document.getElementById("email").textContent=profile.email||"未取得";document.getElementById("username").textContent=profile.username||"未取得";message.textContent=data.registered?"":"表示名を確認して保存してください。";}catch(error){message.textContent=`プロフィールを取得できませんでした：${error.message}`;edit.disabled=true;}}
edit.onclick=()=>editing(true);input.oninput=()=>{dirty=input.value!==original;message.textContent="";};document.getElementById("cancel-button").onclick=()=>{input.value=original;dirty=false;editing(false);message.textContent="変更を取り消しました。";};document.getElementById("save-button").onclick=async()=>{if(saving)return;const error=validate(input.value);if(error){message.textContent=error;return;}const name=input.value.trim();if(name===original){dirty=false;editing(false);message.textContent="変更はありません。";return;}saving=true;document.getElementById("save-button").disabled=true;try{const response=await fetch(api,{method:"PUT",headers:{"Content-Type":"application/json",Authorization:`Bearer ${user.access_token}`},body:JSON.stringify({display_name:name})}),data=await response.json();if(!response.ok)throw new Error(data.message);original=data.user.display_name;input.value=original;value.textContent=original;user.profile.display_name=original;setProfileDisplay(document.getElementById("user-status"),user,"ログイン中：");dirty=false;editing(false);message.textContent="プロフィールを保存しました。";}catch(error){message.textContent=`保存できませんでした：${error.message}`;}finally{saving=false;document.getElementById("save-button").disabled=false;}};
window.addEventListener("beforeunload",event=>{if(dirty){event.preventDefault();event.returnValue="";}});document.getElementById("logout-button").onclick=logout;init();
