import {getCurrentUser,handleSigninCallback,login,logout} from "./auth.js";
import {profileDisplayName} from "./display-utils.js";
import {createDynamicFilters,matchesFilter} from "./dynamic-filters.js";
const apiUrl="https://ba2lg9ckm9.execute-api.ap-northeast-1.amazonaws.com/projects";
const fields={number:{label:"プロジェクト番号",type:"number",get:p=>p.project_number},name:{label:"プロジェクト名",type:"text",get:p=>p.project_name},manager:{label:"責任者",type:"select",get:p=>p.manager},status:{label:"状態",type:"select",get:p=>p.status,options:[["active","進行中"],["on_hold","保留"],["completed","完了"]]},start:{label:"開始日",type:"date",get:p=>p.start_date},end:{label:"終了予定日",type:"date",get:p=>p.end_date}};
const sorts=[["number_asc","プロジェクト番号：昇順"],["number_desc","プロジェクト番号：降順"],["name","プロジェクト名"],["start_desc","開始日：新しい順"],["start_asc","開始日：古い順"],["end_asc","終了予定日：近い順"],["end_desc","終了予定日：遠い順"],["status","状態"]];
let user,allProjects=[];
export function filterAndSortProjects(items,{query,filters,sort}){const q=query.trim().toLocaleLowerCase("ja").replace(/^#/,"");const result=items.filter(p=>{const n=String(p.project_number||"");const text=[n,`#${n}`,p.project_name,p.manager,p.description].filter(Boolean).join(" ").toLocaleLowerCase("ja");return(!q||text.includes(q))&&filters.every(f=>matchesFilter(fields[f.field].get(p),f));});result.sort((a,b)=>{if(sort.startsWith("number"))return(sort.endsWith("desc")?-1:1)*(Number(a.project_number)-Number(b.project_number));if(sort==="name")return String(a.project_name).localeCompare(String(b.project_name),"ja");if(sort.startsWith("start"))return(sort.endsWith("desc")?-1:1)*String(a.start_date||"").localeCompare(String(b.start_date||""));if(sort.startsWith("end"))return(sort.endsWith("desc")?-1:1)*String(a.end_date||"9999").localeCompare(String(b.end_date||"9999"));return String(a.status).localeCompare(String(b.status))||Number(a.project_number)-Number(b.project_number);});return result;}
function render(state){const projects=filterAndSortProjects(allProjects,state),body=document.getElementById("projects-table-body");body.innerHTML="";document.getElementById("list-message").textContent=allProjects.length?`${projects.length}件 / 全${allProjects.length}件を表示`:"登録されたプロジェクトはありません";for(const p of projects){const row=document.createElement("tr"),href=`project_detail.html?id=${encodeURIComponent(p.project_id)}`;for(const [value,link] of [[`${p.project_number||"-"}`,true],[p.project_name||"-",true],[p.manager||"-"],[p.start_date||"-"],[p.end_date||"-"],[{active:"進行中",on_hold:"保留",completed:"完了"}[p.status]||"-"]]){const c=document.createElement("td");if(link){const a=document.createElement("a");a.href=href;a.textContent=value;a.className="table-link";c.appendChild(a);}else c.textContent=value;row.appendChild(c);}body.appendChild(row);}}
async function init(){await handleSigninCallback();user=await getCurrentUser();if(!user||user.expired){document.getElementById("login-button").hidden=false;return;}document.getElementById("user-status").textContent=`ログイン中：${profileDisplayName(user)}`;document.getElementById("logout-button").hidden=false;document.getElementById("projects-section").hidden=false;try{const r=await fetch(apiUrl,{headers:{Authorization:`Bearer ${user.access_token}`}}),d=await r.json();if(!r.ok)throw new Error(d.message);allProjects=d.projects||[];fields.manager.options=[...new Set(allProjects.map(p=>p.manager).filter(Boolean))].map(v=>[v,v]);createDynamicFilters({fields,sorts,defaultSort:"number_asc",onApply:render});}catch(e){document.getElementById("list-message").textContent=e.message;}}
document.getElementById("login-button").onclick=login;document.getElementById("logout-button").onclick=logout;init();
