import {getCurrentUser,logout} from "./auth.js";
import {setProfileDisplay, setUserDisplay, renderChangeHistory} from "./display-utils.js";
import {loadUsers,populateUserSelect,selectedUser,currentName} from "./user-select.js";
const api="https://ba2lg9ckm9.execute-api.ap-northeast-1.amazonaws.com/projects",id=new URLSearchParams(location.search).get("id"),message=document.getElementById("detail-message"),form=document.getElementById("project-edit-form");let user,users=[],project,initial="",dirty=false;
const values=()=>({project_name:document.getElementById("edit-name").value.trim(),...selectedUser(document.getElementById("edit-manager"),users,"manager_id","manager"),status:document.getElementById("edit-status").value,start_date:document.getElementById("edit-start").value,end_date:document.getElementById("edit-end").value,description:document.getElementById("edit-description").value.trim()});
function display(p){project=p;document.getElementById("project-name").textContent=p.project_name;document.getElementById("project-number").textContent=`#${p.project_number||"-"}`;document.getElementById("project-manager").textContent=currentName(p,users,"manager_id","manager");document.getElementById("project-start-date").textContent=p.start_date||"-";document.getElementById("project-end-date").textContent=p.end_date||"未設定";setUserDisplay(document.getElementById("project-created-by"),p.created_by||p.registered_by,user);document.getElementById("project-description").textContent=p.description||"説明は登録されていません。";const status=document.getElementById("project-status");status.textContent={active:"進行中",on_hold:"保留",completed:"完了"}[p.status]||"-";status.className=`status-badge project-status-${p.status}`;const titleStatus=document.getElementById("project-title-status");titleStatus.textContent=`［${status.textContent}］`;titleStatus.className=status.className;document.getElementById("minutes-register-link").href=`register.html?project_id=${encodeURIComponent(p.project_id)}`;renderChangeHistory(document.getElementById("change-history"),p.change_history||[],user);}
function displayMinutes(items){const body=document.getElementById("minutes-table-body");body.innerHTML="";document.getElementById("minutes-message").textContent=items.length?`${items.length}件の議事録`:"関連する議事録はまだありません";for(const m of items){const row=document.createElement("tr"),href=`detail.html?id=${encodeURIComponent(m.minutes_id)}`;for(const [v,linked] of [[`${m.minutes_number}`,true],[m.meeting_name,true],[m.meeting_date],[m.assignee],[{draft:"下書き",pending:"承認待ち",approved:"承認済み",rejected:"差し戻し"}[m.status]]]){const c=document.createElement("td");if(linked){const a=document.createElement("a");a.href=href;a.textContent=v||"-";a.className="table-link";c.appendChild(a);}else c.textContent=v||"-";row.appendChild(c);}body.appendChild(row);}}
function openEdit(){populateUserSelect(document.getElementById("edit-manager"),users,{selectedId:project.manager_id,legacyName:project.manager});const map={"edit-name":project.project_name,"edit-status":project.status,"edit-start":project.start_date,"edit-end":project.end_date,"edit-description":project.description};for(const [k,v] of Object.entries(map))document.getElementById(k).value=v||"";initial=JSON.stringify(values());dirty=false;form.hidden=false;document.getElementById("edit-button").hidden=true;}
async function init(){if(!id)return;user=await getCurrentUser();if(!user||user.expired){location.href="projects.html";return;}setProfileDisplay(document.getElementById("user-status"), user, "ログイン中：");try{users=await loadUsers(user.access_token);const r=await fetch(`${api}/${encodeURIComponent(id)}`,{headers:{Authorization:`Bearer ${user.access_token}`}}),d=await r.json();if(!r.ok)throw new Error(d.message);display(d.project);displayMinutes(d.minutes||[]);message.textContent="";document.getElementById("detail-content").hidden=false;}catch(e){message.textContent=e.message;}}
form.addEventListener("input",()=>dirty=JSON.stringify(values())!==initial);form.onsubmit=async e=>{e.preventDefault();const payload=values();if(payload.end_date&&payload.end_date<payload.start_date){message.textContent="終了予定日は開始日以降にしてください";return;}const b=document.getElementById("save-button");b.disabled=true;try{const r=await fetch(`${api}/${encodeURIComponent(id)}`,{method:"PATCH",headers:{"Content-Type":"application/json",Authorization:`Bearer ${user.access_token}`},body:JSON.stringify(payload)}),d=await r.json();if(!r.ok)throw new Error(d.message);dirty=false;display(d.project);form.hidden=true;document.getElementById("edit-button").hidden=false;message.textContent="更新しました";}catch(e){message.textContent=e.message;}finally{b.disabled=false;}};
document.getElementById("cancel-button").onclick=()=>{if(dirty&&!confirm("未保存の変更を破棄しますか？"))return;dirty=false;form.hidden=true;document.getElementById("edit-button").hidden=false;};window.addEventListener("beforeunload",e=>{if(dirty){e.preventDefault();e.returnValue="";}});document.getElementById("edit-button").onclick=openEdit;document.getElementById("logout-button").onclick=logout;init();
