import test from "node:test";import assert from "node:assert/strict";import {isMyTask,myTaskOrder,taskCounts,dueDateState} from "./task-utils.js";import {isMyTasksSearch,completedFromSearch,searchUrl} from "./url-utils.js";import {formatLocalDateTime} from "./display-utils.js";
test("my task uses id only",()=>{assert.equal(isMyTask({assignee_id:"a",assignee:"同名"},"a"),true);assert.equal(isMyTask({assignee:"同名"},"a"),false);});
test("my task default order",()=>{const tasks=[{task_number:"4",status:"completed",due_date:"2026-01-01"},{task_number:"3",status:"not_started"},{task_number:"2",status:"not_started",due_date:"2026-09-06"},{task_number:"1",status:"in_progress",due_date:"2026-09-01"}];assert.deepEqual(tasks.sort((a,b)=>myTaskOrder(a,b,"2026-09-04")).map(t=>t.task_number),["1","2","3","4"]);});
test("dashboard counts",()=>{assert.deepEqual(taskCounts([{status:"not_started",due_date:"2026-09-01"},{status:"in_progress",due_date:"2026-09-08"}],"2026-09-04"),{not_started:1,in_progress:1,overdue:1,due_soon:1});});
test("URL selects exactly the intended task menu",()=>{assert.equal(isMyTasksSearch("?assignee=me"),true);assert.equal(isMyTasksSearch("?q=x"),false);});
test("task operations retain unrelated params",()=>{for(const changes of [{filtersOpen:"1"},{filters:"[]"},{filters:null},{sort:"due_desc"},{showCompleted:"1"}])assert.match(searchUrl("/tasks.html","?assignee=me&q=x",changes),/assignee=me/);assert.doesNotMatch(searchUrl("/tasks.html","?q=x",{sort:"due_asc"}),/assignee=me/);});
test("completed display URL is saved and restored only in my tasks",()=>{assert.equal(completedFromSearch("?assignee=me&showCompleted=1"),true);assert.equal(completedFromSearch("?showCompleted=1"),false);});
test("due date states include text and exclude completed",()=>{assert.equal(dueDateState({status:"not_started",due_date:"2026-09-03"},"2026-09-04").kind,"overdue");assert.equal(dueDateState({status:"not_started",due_date:"2026-09-04"},"2026-09-04").kind,"today");assert.equal(dueDateState({status:"in_progress",due_date:"2026-09-11"},"2026-09-04").kind,"soon");assert.equal(dueDateState({status:"not_started"},"2026-09-04"),null);assert.equal(dueDateState({status:"completed",due_date:"2026-09-01"},"2026-09-04"),null);});
test("UTC timestamps format locally and invalid values are safe",()=>{assert.notEqual(formatLocalDateTime("2026-09-04T03:06:10.729675+00:00"),"-");assert.equal(formatLocalDateTime("invalid"),"-");assert.equal(formatLocalDateTime(""),"-");});
