import {getCurrentUser,handleSigninCallback,login,logout} from "./auth.js";
import {setProfileDisplay} from "./display-utils.js";
import {createDynamicFilters,matchesFilter} from "./dynamic-filters.js";
import {isMyTask,myTaskOrder} from "./task-utils.js";
import {loadUsers,currentName} from "./user-select.js";
const root="https://ba2lg9ckm9.execute-api.ap-northeast-1.amazonaws.com",api=`${root}/tasks`,labels={not_started:"未着手",in_progress:"進行中",completed:"完了",low:"低",normal:"通常",high:"高",urgent:"緊急"};let allTasks=[],users=[],myMode=false,showCompleted=true;
const fields={number:{label:"チケット番号",type:"number",get:t=>t.task_number},title:{label:"件名",type:"text",get:t=>t.title},project:{label:"プロジェクト",type:"select",get:t=>t.project_id},assignee:{label:"担当者",type:"select",get:t=>t.assignee_id||t.assignee},status:{label:"状態",type:"select",get:t=>t.status,options:[["not_started","未着手"],["in_progress","進行中"],["completed","完了"]]},priority:{label:"優先度",type:"select",get:t=>t.priority,options:[["low","低"],["normal","通常"],["high","高"],["urgent","緊急"]]},due:{label:"期限",type:"date",get:t=>t.due_date}};
const sorts=[["number_asc","チケット番号：昇順"],["number_desc","チケット番号：降順"],["due_asc","期限：近い順"],["due_desc","期限：遠い順"],["priority","優先度"],["status","状態"]];
export function filterAndSortTasks(tasks,{query,filters,sort}){const q=query.trim().toLowerCase().replace(/^#/,"");const result=tasks.filter(t=>{const text=[t.task_number,t.title,t.description,t.project_name,t.assignee,t.resolution].filter(Boolean).join(" ").toLowerCase();return(!q||text.includes(q))&&filters.every(row=>matchesFilter(fields[row.field].get(t),row));});if(myMode)return result.sort(myTaskOrder);return result.sort((a,b)=>sort.startsWith("number")?(sort.endsWith("desc")?-1:1)*(Number(a.task_number)-Number(b.task_number)):sort.startsWith("due")?(a.due_date||"9999").localeCompare(b.due_date||"9999")*(sort.endsWith("desc")?-1:1):Number(a.task_number)-Number(b.task_number));}
function render(state){let tasks=filterAndSortTasks(allTasks,state);if(myMode&&!showCompleted)tasks=tasks.filter(t=>t.status!=="completed");const body=document.getElementById("tasks-table-body");body.replaceChildren();document.getElementById("list-message").textContent=tasks.length?`${tasks.length}件 / 全${allTasks.length}件を表示`:"対象なし";for(const t of tasks){const row=document.createElement("tr"),href=`task_detail.html?id=${encodeURIComponent(t.task_id)}&return_to=${encodeURIComponent(location.pathname+location.search)}`;for(const [value,linked] of [[t.task_number,true],[t.title,true],[t.project_name],[t.due_date||"期限なし"],[labels[t.status]||t.status],[labels[t.priority]||t.priority]]){const cell=document.createElement("td");if(linked){const a=document.createElement("a");a.href=href;a.textContent=value||"-";cell.append(a);}else cell.textContent=value||"-";row.append(cell);}body.append(row);}}
async function init(){await handleSigninCallback();const user=await getCurrentUser();if(!user||user.expired){document.getElementById("login-button").hidden=false;return;}setProfileDisplay(document.getElementById("user-status"),user,"ログイン中：");document.getElementById("logout-button").hidden=false;document.getElementById("tasks-section").hidden=false;myMode=new URLSearchParams(location.search).get("assignee")==="me";if(myMode){document.querySelector("h1").textContent="自分のチケット";const toggle=document.createElement("label");toggle.className="completed-toggle";toggle.innerHTML='<input type="checkbox" checked> 完了済みを表示';toggle.firstChild.onchange=e=>{showCompleted=e.target.checked;document.getElementById("apply-filters").click();};document.querySelector(".page-heading").append(toggle);}try{const headers={Authorization:`Bearer ${user.access_token}`},[tr,mr]=await Promise.all([fetch(api,{headers}),fetch(`${root}/minutes`,{headers})]),td=await tr.json(),md=await mr.json();if(!tr.ok)throw new Error(td.message);if(!mr.ok)throw new Error(md.message);try{users=await loadUsers(user.access_token);}catch{users=[];}allTasks=(td.tasks||[]).map(t=>({...t,assignee:currentName(t,users,"assignee_id","assignee")}));if(myMode)allTasks=allTasks.filter(t=>isMyTask(t,user.profile?.sub));fields.project.options=[...new Map(allTasks.filter(t=>t.project_id).map(t=>[t.project_id,[t.project_id,t.project_name]])).values()];fields.assignee.options=[...new Map(allTasks.map(t=>[t.assignee_id||t.assignee,[t.assignee_id||t.assignee,t.assignee]])).values()];createDynamicFilters({fields,sorts,defaultSort:myMode?"due_asc":"number_asc",onApply:render});}catch(e){document.getElementById("list-message").textContent=e.message;}}
document.getElementById("login-button").onclick=login;document.getElementById("logout-button").onclick=logout;init();
