import {getCurrentUser,logout} from "./auth.js";
import {profileDisplayName} from "./display-utils.js";
import {clearDueDate} from "./date-utils.js";
const root="https://ba2lg9ckm9.execute-api.ap-northeast-1.amazonaws.com",id=new URLSearchParams(location.search).get("id"),list=document.getElementById("todo-list"),message=document.getElementById("message");let user,minutes,tasks=[];
const request=async(path,options={})=>{options.headers={...(options.headers||{}),Authorization:`Bearer ${user.access_token}`};const response=await fetch(root+path,options),data=await response.json();if(!response.ok){const error=new Error(data.message||"APIエラー");error.status=response.status;throw error;}return data;};
function card(todo,index){const made=tasks.find(t=>t.source_type==="ai"&&String(t.source_todo_index)===String(index)),li=document.createElement("li");li.className=`todo-card${made?" is-created":""}`;li.dataset.index=index;li.innerHTML=`<div class="todo-card-header"><input class="todo-select" type="checkbox" ${made?"disabled":"checked"} aria-label="TODO候補 ${index+1}を選択"><strong>TODO候補 #${index+1}</strong><span class="todo-status">${made?"作成済み":"未登録"}</span></div><p class="todo-original"></p><div class="todo-meta">担当：${todo.assignee||"未設定"}　期限：${todo.deadline||"未設定"}　優先度：通常</div>`;li.querySelector(".todo-original").textContent=todo.task||todo.description||"（本文なし）";
if(made){const a=document.createElement("a");a.href=`task_detail.html?id=${encodeURIComponent(made.task_id)}`;a.textContent=`チケット ${made.task_number} を開く`;li.appendChild(a);return li;}
const editor=document.createElement("div");editor.className="todo-edit-fields";editor.hidden=true;for(const [name,label,value,type] of [["title","件名",todo.task||"","text"],["description","説明",todo.description||"","textarea"],["assignee","担当者",todo.assignee||"","text"],["due_date","期限",clearDueDate(todo.deadline,minutes.meeting_date),"date"]]){const l=document.createElement("label");l.textContent=label;const input=type==="textarea"?document.createElement("textarea"):document.createElement("input");input.name=name;input.value=value;if(type==="date")input.type="date";l.appendChild(input);editor.appendChild(l);}const l=document.createElement("label");l.textContent="優先度";l.innerHTML+=' <select name="priority"><option value="low">低</option><option value="normal" selected>通常</option><option value="high">高</option><option value="urgent">緊急</option></select>';editor.appendChild(l);li.appendChild(editor);const actions=document.createElement("div");actions.className="todo-actions";const edit=document.createElement("button");edit.type="button";edit.className="action-link";edit.textContent="✎ 内容を編集";edit.onclick=()=>{editor.hidden=!editor.hidden;edit.textContent=editor.hidden?"✎ 内容を編集":"編集を閉じる";};const create=document.createElement("button");create.type="button";create.className="compact-button";create.textContent="チケットに登録";create.onclick=()=>createItems([li]);actions.append(edit,create);li.appendChild(actions);return li;}
function render(){list.innerHTML="";const todos=minutes.ai_minutes?.todos||[];if(!todos.length){message.textContent=minutes.ai_minutes&&Object.keys(minutes.ai_minutes).length?"AI抽出TODOはありません":"AI議事録が未作成です";document.getElementById("create-selected").hidden=true;return;}todos.forEach((t,i)=>list.appendChild(card(t,i)));}
async function createItems(items){const results=[];document.getElementById("create-selected").disabled=true;for(const li of items){li.querySelectorAll("button").forEach(b=>b.disabled=true);const payload={source_minutes_id:id,source_type:"ai",source_todo_index:Number(li.dataset.index)};li.querySelectorAll("[name]").forEach(i=>payload[i.name]=i.value);try{const data=await request("/tasks",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});results.push(`#${data.task.task_number}を作成`);}catch(e){results.push(`候補${Number(li.dataset.index)+1}: ${e.message}`);}}message.textContent=results.join(" / ");await load();document.getElementById("create-selected").disabled=false;}
async function load(){const [md,td]=await Promise.all([request(`/minutes/${encodeURIComponent(id)}`),request(`/tasks?source_minutes_id=${encodeURIComponent(id)}`)]);minutes=md.minutes;tasks=td.tasks||[];document.getElementById("minutes-meta").textContent=`議事録 #${minutes.minutes_number}　${minutes.meeting_name}　／　${minutes.project_name}`;render();}
async function init(){user=await getCurrentUser();if(!user||user.expired||!id){location.href="index.html";return;}document.getElementById("user-status").textContent=`ログイン中：${profileDisplayName(user)}`;document.getElementById("back-link").href=`detail.html?id=${encodeURIComponent(id)}#ai-section`;try{await load();}catch(e){message.textContent=e.message;}}
document.getElementById("create-selected").onclick=()=>createItems([...document.querySelectorAll(".todo-card:not(.is-created)")].filter(li=>li.querySelector(".todo-select").checked));document.getElementById("logout-button").onclick=logout;init();
